/*This file was generated by NativeWind. Do not edit!*/
const {
  NativeWindStyleSheet: _NativeWindStyleSheet
} = require("nativewind");

_NativeWindStyleSheet.create({
  styles: {
    "*": {
      "borderTopWidth": 0,
      "borderRightWidth": 0,
      "borderBottomWidth": 0,
      "borderLeftWidth": 0,
      "borderStyle": "solid",
      "borderTopColor": "#e5e7eb",
      "borderRightColor": "#e5e7eb",
      "borderBottomColor": "#e5e7eb",
      "borderLeftColor": "#e5e7eb"
    },
    "": {
      "borderTopWidth": 0,
      "borderRightWidth": 0,
      "borderBottomWidth": 0,
      "borderLeftWidth": 0,
      "borderStyle": "solid",
      "borderTopColor": "#e5e7eb",
      "borderRightColor": "#e5e7eb",
      "borderBottomColor": "#e5e7eb",
      "borderLeftColor": "#e5e7eb"
    },
    "html": {
      "lineHeight": 1.5,
      "fontFamily": "ui-sans-serif"
    },
    "body": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "hr": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "abbr:where([title])": {
      "textDecorationLine": "underline",
      "textDecorationColor": "black",
      "textDecorationStyle": "dotted"
    },
    "code": {
      "fontFamily": "ui-monospace",
      "fontSize": "1em"
    },
    "kbd": {
      "fontFamily": "ui-monospace",
      "fontSize": "1em"
    },
    "samp": {
      "fontFamily": "ui-monospace",
      "fontSize": "1em"
    },
    "pre": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "small": {
      "fontSize": "80%"
    },
    "sub": {
      "fontSize": "75%",
      "lineHeight": 0,
      "position": "relative"
    },
    "sup": {
      "fontSize": "75%",
      "lineHeight": 0,
      "position": "relative"
    },
    "button": {
      "backgroundColor": "transparent"
    },
    "input": {
      "opacity": 1,
      "color": "#9ca3af"
    },
    "optgroup": {
      "fontFamily": "inherit",
      "fontSize": "100%",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0
    },
    "select": {
      "textTransform": "none"
    },
    "textarea": {
      "opacity": 1,
      "color": "#9ca3af"
    },
    "[type='button']": {
      "backgroundColor": "transparent"
    },
    "[type='reset']": {
      "backgroundColor": "transparent"
    },
    "[type='submit']": {
      "backgroundColor": "transparent"
    },
    ":-moz-ui-invalid": {
      "shadowOffset": {
        "width": 0,
        "height": 0
      },
      "shadowRadius": 0,
      "shadowColor": "black",
      "shadowOpacity": 1
    },
    "blockquote": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "dl": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "dd": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "h1": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "h2": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "h3": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "h4": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "h5": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "h6": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "figure": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "p": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "fieldset": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0
    },
    "legend": {
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0
    },
    "ol": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0
    },
    "ul": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0
    },
    "menu": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0
    },
    "img": {
      "maxWidth": "100%"
    },
    "video": {
      "maxWidth": "100%"
    },
    "container": {
      "width": "100%"
    },
    "container@0": {
      "maxWidth": 640
    },
    "container@1": {
      "maxWidth": 768
    },
    "container@2": {
      "maxWidth": 1024
    },
    "container@3": {
      "maxWidth": 1280
    },
    "container@4": {
      "maxWidth": 1536
    },
    "shadow-xl@0": {
      "elevation": 12.5,
      "shadowColor": "rgba(0, 0, 0, 0.1)"
    },
    "shadow-xl@1": {
      "shadowOffset": {
        "width": 0,
        "height": 20
      },
      "shadowRadius": 25,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow-xl@2": {
      "shadowOffset": {
        "width": 0,
        "height": 20
      },
      "shadowRadius": 25,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "absolute": {
      "position": "absolute"
    },
    "relative": {
      "position": "relative"
    },
    "top-10": {
      "top": 40
    },
    "top-6": {
      "top": 24
    },
    "left-4": {
      "left": 16
    },
    "left-8": {
      "left": 32
    },
    "z-10": {
      "zIndex": 10
    },
    "z-0": {
      "zIndex": 0
    },
    "m-10": {
      "marginTop": 40,
      "marginRight": 40,
      "marginBottom": 40,
      "marginLeft": 40
    },
    "m-2": {
      "marginTop": 8,
      "marginRight": 8,
      "marginBottom": 8,
      "marginLeft": 8
    },
    "m-3": {
      "marginTop": 12,
      "marginRight": 12,
      "marginBottom": 12,
      "marginLeft": 12
    },
    "m-4": {
      "marginTop": 16,
      "marginRight": 16,
      "marginBottom": 16,
      "marginLeft": 16
    },
    "m-6": {
      "marginTop": 24,
      "marginRight": 24,
      "marginBottom": 24,
      "marginLeft": 24
    },
    "m-0": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "m-5": {
      "marginTop": 20,
      "marginRight": 20,
      "marginBottom": 20,
      "marginLeft": 20
    },
    "my-2": {
      "marginTop": 8,
      "marginBottom": 8
    },
    "mx-5": {
      "marginLeft": 20,
      "marginRight": 20
    },
    "my-5": {
      "marginTop": 20,
      "marginBottom": 20
    },
    "mb-10": {
      "marginBottom": 40
    },
    "mt-5": {
      "marginTop": 20
    },
    "ml-[10px]": {
      "marginLeft": 10
    },
    "mt-4": {
      "marginTop": 16
    },
    "ml-4": {
      "marginLeft": 16
    },
    "mr-7": {
      "marginRight": 28
    },
    "mt-10": {
      "marginTop": 40
    },
    "ml-8": {
      "marginLeft": 32
    },
    "h-[45px]": {
      "height": 45
    },
    "h-screen": {
      "height": 100
    },
    "h-1/2": {
      "height": "50%"
    },
    "h-1/3": {
      "height": "33.333333%"
    },
    "h-1/4": {
      "height": "25%"
    },
    "w-11/12": {
      "width": "91.666667%"
    },
    "w-[45px]": {
      "width": 45
    },
    "w-10/12": {
      "width": "83.333333%"
    },
    "min-w-[90%]": {
      "minWidth": "90%"
    },
    "max-w-[90%]": {
      "maxWidth": "90%"
    },
    "flex-1": {
      "flexGrow": 1,
      "flexShrink": 1
    },
    "grow": {
      "flexGrow": 1
    },
    "flex-row": {
      "flexDirection": "row"
    },
    "items-center": {
      "alignItems": "center"
    },
    "justify-center": {
      "justifyContent": "center"
    },
    "justify-between": {
      "justifyContent": "space-between"
    },
    "self-start": {
      "alignSelf": "flex-start"
    },
    "self-end": {
      "alignSelf": "flex-end"
    },
    "self-center": {
      "alignSelf": "center"
    },
    "rounded-xl": {
      "borderTopLeftRadius": 12,
      "borderTopRightRadius": 12,
      "borderBottomRightRadius": 12,
      "borderBottomLeftRadius": 12
    },
    "border-2": {
      "borderTopWidth": 2,
      "borderRightWidth": 2,
      "borderBottomWidth": 2,
      "borderLeftWidth": 2
    },
    "border-black": {
      "borderTopColor": "#000",
      "borderRightColor": "#000",
      "borderBottomColor": "#000",
      "borderLeftColor": "#000"
    },
    "border-white": {
      "borderTopColor": "#fff",
      "borderRightColor": "#fff",
      "borderBottomColor": "#fff",
      "borderLeftColor": "#fff"
    },
    "bg-primary": {
      "backgroundColor": "#EEA734"
    },
    "bg-gray-200": {
      "backgroundColor": "#e5e7eb"
    },
    "bg-white": {
      "backgroundColor": "#fff"
    },
    "bg-background": {
      "backgroundColor": "#FFF8EE"
    },
    "py-4": {
      "paddingTop": 16,
      "paddingBottom": 16
    },
    "px-4": {
      "paddingLeft": 16,
      "paddingRight": 16
    },
    "py-5": {
      "paddingTop": 20,
      "paddingBottom": 20
    },
    "text-center": {
      "textAlign": "center"
    },
    "font-displayMedium": {
      "fontFamily": "Inter-Medium"
    },
    "font-displayBold": {
      "fontFamily": "Inter-Bold"
    },
    "font-display": {
      "fontFamily": "Inter-Regular"
    },
    "text-black": {
      "color": "#000"
    },
    "text-white": {
      "color": "#fff"
    },
    "text-primary": {
      "color": "#EEA734"
    },
    "text-xl": {
      "fontSize": 20,
      "lineHeight": 28
    },
    "text-sm": {
      "fontSize": 14,
      "lineHeight": 20
    },
    "text-4xl": {
      "fontSize": 36,
      "lineHeight": 40
    },
    "text-base": {
      "fontSize": 16,
      "lineHeight": 24
    },
    "text-3xl": {
      "fontSize": 30,
      "lineHeight": 36
    },
    "text-2xl": {
      "fontSize": 24,
      "lineHeight": 32
    },
    "text-lg": {
      "fontSize": 18,
      "lineHeight": 28
    },
    "container@5": {
      "maxWidth": 640
    },
    "container@6": {
      "maxWidth": 768
    },
    "container@7": {
      "maxWidth": 1024
    },
    "container@8": {
      "maxWidth": 1280
    },
    "container@9": {
      "maxWidth": 1536
    },
    "shadow-xl@3": {
      "elevation": 12.5,
      "shadowColor": "rgba(0, 0, 0, 0.1)"
    },
    "shadow-xl@4": {
      "shadowOffset": {
        "width": 0,
        "height": 20
      },
      "shadowRadius": 25,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow-xl@5": {
      "shadowOffset": {
        "width": 0,
        "height": 20
      },
      "shadowRadius": 25,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    }
  },
  atRules: {
    "container": [[["media", "(min-width: 640px)"]], [["media", "(min-width: 768px)"]], [["media", "(min-width: 1024px)"]], [["media", "(min-width: 1280px)"]], [["media", "(min-width: 1536px)"]], [["media", "(min-width: 640px)"]], [["media", "(min-width: 768px)"]], [["media", "(min-width: 1024px)"]], [["media", "(min-width: 1280px)"]], [["media", "(min-width: 1536px)"]]],
    "shadow-xl": [[["media", "android"]], [["media", "ios"]], [["media", "web"]], [["media", "android"]], [["media", "ios"]], [["media", "web"]]]
  },
  topics: {
    "container": ["width"],
    "h-screen": ["height"]
  },
  units: {
    "h-screen": {
      "height": "vh"
    }
  }
});