/*This file was generated by NativeWind. Do not edit!*/
const {
  NativeWindStyleSheet: _NativeWindStyleSheet
} = require("nativewind");

_NativeWindStyleSheet.create({
  styles: {
    "*": {
      "borderTopWidth": 0,
      "borderRightWidth": 0,
      "borderBottomWidth": 0,
      "borderLeftWidth": 0,
      "borderStyle": "solid",
      "borderTopColor": "#e5e7eb",
      "borderRightColor": "#e5e7eb",
      "borderBottomColor": "#e5e7eb",
      "borderLeftColor": "#e5e7eb"
    },
    "": {
      "borderTopWidth": 0,
      "borderRightWidth": 0,
      "borderBottomWidth": 0,
      "borderLeftWidth": 0,
      "borderStyle": "solid",
      "borderTopColor": "#e5e7eb",
      "borderRightColor": "#e5e7eb",
      "borderBottomColor": "#e5e7eb",
      "borderLeftColor": "#e5e7eb"
    },
    "html": {
      "lineHeight": 1.5,
      "fontFamily": "ui-sans-serif"
    },
    "body": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "hr": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "abbr:where([title])": {
      "textDecorationLine": "underline",
      "textDecorationColor": "black",
      "textDecorationStyle": "dotted"
    },
    "code": {
      "fontFamily": "ui-monospace",
      "fontSize": "1em"
    },
    "kbd": {
      "fontFamily": "ui-monospace",
      "fontSize": "1em"
    },
    "samp": {
      "fontFamily": "ui-monospace",
      "fontSize": "1em"
    },
    "pre": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "small": {
      "fontSize": "80%"
    },
    "sub": {
      "fontSize": "75%",
      "lineHeight": 0,
      "position": "relative"
    },
    "sup": {
      "fontSize": "75%",
      "lineHeight": 0,
      "position": "relative"
    },
    "button": {
      "backgroundColor": "transparent"
    },
    "input": {
      "opacity": 1,
      "color": "#9ca3af"
    },
    "optgroup": {
      "fontFamily": "inherit",
      "fontSize": "100%",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0
    },
    "select": {
      "textTransform": "none"
    },
    "textarea": {
      "opacity": 1,
      "color": "#9ca3af"
    },
    "[type='button']": {
      "backgroundColor": "transparent"
    },
    "[type='reset']": {
      "backgroundColor": "transparent"
    },
    "[type='submit']": {
      "backgroundColor": "transparent"
    },
    ":-moz-ui-invalid": {
      "shadowOffset": {
        "width": 0,
        "height": 0
      },
      "shadowRadius": 0,
      "shadowColor": "black",
      "shadowOpacity": 1
    },
    "blockquote": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "dl": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "dd": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "h1": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "h2": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "h3": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "h4": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "h5": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "h6": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "figure": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "p": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "fieldset": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0
    },
    "legend": {
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0
    },
    "ol": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0
    },
    "ul": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0
    },
    "menu": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0
    },
    "img": {
      "maxWidth": "100%"
    },
    "video": {
      "maxWidth": "100%"
    },
    "relative": {
      "position": "relative"
    },
    "top-6": {
      "top": 24
    },
    "left-7": {
      "left": 28
    },
    "z-10": {
      "zIndex": 10
    },
    "z-0": {
      "zIndex": 0
    },
    "my-3": {
      "marginTop": 12,
      "marginBottom": 12
    },
    "w-11/12": {
      "width": "91.666667%"
    },
    "min-w-[90%]": {
      "minWidth": "90%"
    },
    "max-w-[90%]": {
      "maxWidth": "90%"
    },
    "flex-1": {
      "flexGrow": 1,
      "flexShrink": 1
    },
    "items-center": {
      "alignItems": "center"
    },
    "justify-center": {
      "justifyContent": "center"
    },
    "self-center": {
      "alignSelf": "center"
    },
    "rounded-xl": {
      "borderTopLeftRadius": 12,
      "borderTopRightRadius": 12,
      "borderBottomRightRadius": 12,
      "borderBottomLeftRadius": 12
    },
    "border": {
      "borderTopWidth": 1,
      "borderRightWidth": 1,
      "borderBottomWidth": 1,
      "borderLeftWidth": 1
    },
    "border-black": {
      "borderTopColor": "#000",
      "borderRightColor": "#000",
      "borderBottomColor": "#000",
      "borderLeftColor": "#000"
    },
    "border-gray-500": {
      "borderTopColor": "#6b7280",
      "borderRightColor": "#6b7280",
      "borderBottomColor": "#6b7280",
      "borderLeftColor": "#6b7280"
    },
    "bg-primary": {
      "backgroundColor": "#EEA734"
    },
    "bg-gray-200": {
      "backgroundColor": "#e5e7eb"
    },
    "bg-white": {
      "backgroundColor": "#fff"
    },
    "bg-[#FFFFED]": {
      "backgroundColor": "#FFFFED"
    },
    "py-4": {
      "paddingTop": 16,
      "paddingBottom": 16
    },
    "px-4": {
      "paddingLeft": 16,
      "paddingRight": 16
    },
    "py-5": {
      "paddingTop": 20,
      "paddingBottom": 20
    },
    "font-display": {
      "fontFamily": "Montserrat-Regular"
    },
    "text-white": {
      "color": "#fff"
    },
    "text-black": {
      "color": "#000"
    },
    "text-xl": {
      "fontSize": 20,
      "lineHeight": 28
    },
    "text-sm": {
      "fontSize": 14,
      "lineHeight": 20
    },
    "w-[75%]": {
      "width": "75%"
    },
    "w-[70%]": {
      "width": "70%"
    },
    "h-1/2": {
      "height": "50%"
    },
    "m-2": {
      "marginTop": 8,
      "marginRight": 8,
      "marginBottom": 8,
      "marginLeft": 8
    },
    "m-10": {
      "marginTop": 40,
      "marginRight": 40,
      "marginBottom": 40,
      "marginLeft": 40
    },
    "h-1/4": {
      "height": "25%"
    },
    "font-bold": {
      "fontWeight": "700"
    },
    "text-4xl": {
      "fontSize": 36,
      "lineHeight": 40
    },
    "text-3xl": {
      "fontSize": 30,
      "lineHeight": 36
    },
    "font-displayBold": {
      "fontFamily": "Montserrat-Bold"
    },
    "text-lg": {
      "fontSize": 18,
      "lineHeight": 28
    },
    "text-base": {
      "fontSize": 16,
      "lineHeight": 24
    },
    "m-4": {
      "marginTop": 16,
      "marginRight": 16,
      "marginBottom": 16,
      "marginLeft": 16
    },
    "m-6": {
      "marginTop": 24,
      "marginRight": 24,
      "marginBottom": 24,
      "marginLeft": 24
    },
    "text-center": {
      "textAlign": "center"
    },
    "bg-[#FFFFFF]": {
      "backgroundColor": "#FFFFFF"
    },
    "bg-[#FEFBEA]": {
      "backgroundColor": "#FEFBEA"
    },
    "bg-[#FFFCC9]": {
      "backgroundColor": "#FFFCC9"
    },
    "bg-[#FFF8EE]": {
      "backgroundColor": "#FFF8EE"
    },
    "bg-background": {
      "backgroundColor": "#FFF8EE"
    },
    "h-1/3": {
      "height": "33.333333%"
    },
    "w-1/4": {
      "width": "25%"
    },
    "w-1/2": {
      "width": "50%"
    },
    "text-2xl": {
      "fontSize": 24,
      "lineHeight": 32
    },
    "m-3": {
      "marginTop": 12,
      "marginRight": 12,
      "marginBottom": 12,
      "marginLeft": 12
    },
    "m-5": {
      "marginTop": 20,
      "marginRight": 20,
      "marginBottom": 20,
      "marginLeft": 20
    },
    "border-primary": {
      "borderTopColor": "#EEA734",
      "borderRightColor": "#EEA734",
      "borderBottomColor": "#EEA734",
      "borderLeftColor": "#EEA734"
    },
    "border-[#EEA734]": {
      "borderTopColor": "#EEA734",
      "borderRightColor": "#EEA734",
      "borderBottomColor": "#EEA734",
      "borderLeftColor": "#EEA734"
    },
    "border-slate-400": {
      "borderTopColor": "#94a3b8",
      "borderRightColor": "#94a3b8",
      "borderBottomColor": "#94a3b8",
      "borderLeftColor": "#94a3b8"
    },
    "border-indigo-400": {
      "borderTopColor": "#818cf8",
      "borderRightColor": "#818cf8",
      "borderBottomColor": "#818cf8",
      "borderLeftColor": "#818cf8"
    },
    "border-indigo-200": {
      "borderTopColor": "#c7d2fe",
      "borderRightColor": "#c7d2fe",
      "borderBottomColor": "#c7d2fe",
      "borderLeftColor": "#c7d2fe"
    },
    "border-2": {
      "borderTopWidth": 2,
      "borderRightWidth": 2,
      "borderBottomWidth": 2,
      "borderLeftWidth": 2
    },
    "border-rose-500": {
      "borderTopColor": "#f43f5e",
      "borderRightColor": "#f43f5e",
      "borderBottomColor": "#f43f5e",
      "borderLeftColor": "#f43f5e"
    },
    "border-white": {
      "borderTopColor": "#fff",
      "borderRightColor": "#fff",
      "borderBottomColor": "#fff",
      "borderLeftColor": "#fff"
    },
    "border-background": {
      "borderTopColor": "#FFF8EE",
      "borderRightColor": "#FFF8EE",
      "borderBottomColor": "#FFF8EE",
      "borderLeftColor": "#FFF8EE"
    },
    "border-secondary": {
      "borderTopColor": "#EEA374",
      "borderRightColor": "#EEA374",
      "borderBottomColor": "#EEA374",
      "borderLeftColor": "#EEA374"
    },
    "shadow@0": {
      "elevation": 3,
      "shadowColor": "rgba(0, 0, 0, 0.1)"
    },
    "shadow@1": {
      "shadowOffset": {
        "width": 0,
        "height": 2
      },
      "shadowRadius": 6,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow@2": {
      "shadowOffset": {
        "width": 0,
        "height": 2
      },
      "shadowRadius": 6,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow@3": {
      "elevation": 3,
      "shadowColor": "rgba(0, 0, 0, 0.1)"
    },
    "shadow-2xl@0": {
      "elevation": 25,
      "shadowColor": "rgba(0, 0, 0, 0.1)"
    },
    "shadow@4": {
      "shadowOffset": {
        "width": 0,
        "height": 2
      },
      "shadowRadius": 6,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow-2xl@1": {
      "shadowOffset": {
        "width": 0,
        "height": 25
      },
      "shadowRadius": 50,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow@5": {
      "shadowOffset": {
        "width": 0,
        "height": 2
      },
      "shadowRadius": 6,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow-2xl@2": {
      "shadowOffset": {
        "width": 0,
        "height": 25
      },
      "shadowRadius": 50,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow@6": {
      "elevation": 3,
      "shadowColor": "rgba(0, 0, 0, 0.1)"
    },
    "shadow-xl@0": {
      "elevation": 12.5,
      "shadowColor": "rgba(0, 0, 0, 0.1)"
    },
    "shadow-2xl@3": {
      "elevation": 25,
      "shadowColor": "rgba(0, 0, 0, 0.1)"
    },
    "shadow@7": {
      "shadowOffset": {
        "width": 0,
        "height": 2
      },
      "shadowRadius": 6,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow-xl@1": {
      "shadowOffset": {
        "width": 0,
        "height": 20
      },
      "shadowRadius": 25,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow-2xl@4": {
      "shadowOffset": {
        "width": 0,
        "height": 25
      },
      "shadowRadius": 50,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow@8": {
      "shadowOffset": {
        "width": 0,
        "height": 2
      },
      "shadowRadius": 6,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow-xl@2": {
      "shadowOffset": {
        "width": 0,
        "height": 20
      },
      "shadowRadius": 25,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow-2xl@5": {
      "shadowOffset": {
        "width": 0,
        "height": 25
      },
      "shadowRadius": 50,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow@9": {
      "elevation": 3,
      "shadowColor": "rgba(0, 0, 0, 0.1)"
    },
    "shadow-xl@3": {
      "elevation": 12.5,
      "shadowColor": "rgba(0, 0, 0, 0.1)"
    },
    "shadow-2xl@6": {
      "elevation": 25,
      "shadowColor": "rgba(0, 0, 0, 0.1)"
    },
    "shadow@10": {
      "shadowOffset": {
        "width": 0,
        "height": 2
      },
      "shadowRadius": 6,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow-xl@4": {
      "shadowOffset": {
        "width": 0,
        "height": 20
      },
      "shadowRadius": 25,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow-2xl@7": {
      "shadowOffset": {
        "width": 0,
        "height": 25
      },
      "shadowRadius": 50,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow@11": {
      "shadowOffset": {
        "width": 0,
        "height": 2
      },
      "shadowRadius": 6,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow-xl@5": {
      "shadowOffset": {
        "width": 0,
        "height": 20
      },
      "shadowRadius": 25,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow-2xl@8": {
      "shadowOffset": {
        "width": 0,
        "height": 25
      },
      "shadowRadius": 50,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "left-6": {
      "left": 24
    },
    "shadow@12": {
      "elevation": 3,
      "shadowColor": "rgba(0, 0, 0, 0.1)"
    },
    "shadow-xl@6": {
      "elevation": 12.5,
      "shadowColor": "rgba(0, 0, 0, 0.1)"
    },
    "shadow-2xl@9": {
      "elevation": 25,
      "shadowColor": "rgba(0, 0, 0, 0.1)"
    },
    "shadow@13": {
      "shadowOffset": {
        "width": 0,
        "height": 2
      },
      "shadowRadius": 6,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow-xl@7": {
      "shadowOffset": {
        "width": 0,
        "height": 20
      },
      "shadowRadius": 25,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow-2xl@10": {
      "shadowOffset": {
        "width": 0,
        "height": 25
      },
      "shadowRadius": 50,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow@14": {
      "shadowOffset": {
        "width": 0,
        "height": 2
      },
      "shadowRadius": 6,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow-xl@8": {
      "shadowOffset": {
        "width": 0,
        "height": 20
      },
      "shadowRadius": 25,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow-2xl@11": {
      "shadowOffset": {
        "width": 0,
        "height": 25
      },
      "shadowRadius": 50,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "left-2": {
      "left": 8
    },
    "shadow@15": {
      "elevation": 3,
      "shadowColor": "rgba(0, 0, 0, 0.1)"
    },
    "shadow-xl@9": {
      "elevation": 12.5,
      "shadowColor": "rgba(0, 0, 0, 0.1)"
    },
    "shadow-2xl@12": {
      "elevation": 25,
      "shadowColor": "rgba(0, 0, 0, 0.1)"
    },
    "shadow@16": {
      "shadowOffset": {
        "width": 0,
        "height": 2
      },
      "shadowRadius": 6,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow-xl@10": {
      "shadowOffset": {
        "width": 0,
        "height": 20
      },
      "shadowRadius": 25,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow-2xl@13": {
      "shadowOffset": {
        "width": 0,
        "height": 25
      },
      "shadowRadius": 50,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow@17": {
      "shadowOffset": {
        "width": 0,
        "height": 2
      },
      "shadowRadius": 6,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow-xl@11": {
      "shadowOffset": {
        "width": 0,
        "height": 20
      },
      "shadowRadius": 25,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow-2xl@14": {
      "shadowOffset": {
        "width": 0,
        "height": 25
      },
      "shadowRadius": 50,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "left-4": {
      "left": 16
    },
    "shadow@18": {
      "elevation": 3,
      "shadowColor": "rgba(0, 0, 0, 0.1)"
    },
    "shadow-xl@12": {
      "elevation": 12.5,
      "shadowColor": "rgba(0, 0, 0, 0.1)"
    },
    "shadow-2xl@15": {
      "elevation": 25,
      "shadowColor": "rgba(0, 0, 0, 0.1)"
    },
    "shadow@19": {
      "shadowOffset": {
        "width": 0,
        "height": 2
      },
      "shadowRadius": 6,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow-xl@13": {
      "shadowOffset": {
        "width": 0,
        "height": 20
      },
      "shadowRadius": 25,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow-2xl@16": {
      "shadowOffset": {
        "width": 0,
        "height": 25
      },
      "shadowRadius": 50,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow@20": {
      "shadowOffset": {
        "width": 0,
        "height": 2
      },
      "shadowRadius": 6,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow-xl@14": {
      "shadowOffset": {
        "width": 0,
        "height": 20
      },
      "shadowRadius": 25,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow-2xl@17": {
      "shadowOffset": {
        "width": 0,
        "height": 25
      },
      "shadowRadius": 50,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow@21": {
      "elevation": 3,
      "shadowColor": "rgba(0, 0, 0, 0.1)"
    },
    "shadow-xl@15": {
      "elevation": 12.5,
      "shadowColor": "rgba(0, 0, 0, 0.1)"
    },
    "shadow-2xl@18": {
      "elevation": 25,
      "shadowColor": "rgba(0, 0, 0, 0.1)"
    },
    "shadow@22": {
      "shadowOffset": {
        "width": 0,
        "height": 2
      },
      "shadowRadius": 6,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow-xl@16": {
      "shadowOffset": {
        "width": 0,
        "height": 20
      },
      "shadowRadius": 25,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow-2xl@19": {
      "shadowOffset": {
        "width": 0,
        "height": 25
      },
      "shadowRadius": 50,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow@23": {
      "shadowOffset": {
        "width": 0,
        "height": 2
      },
      "shadowRadius": 6,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow-xl@17": {
      "shadowOffset": {
        "width": 0,
        "height": 20
      },
      "shadowRadius": 25,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow-2xl@20": {
      "shadowOffset": {
        "width": 0,
        "height": 25
      },
      "shadowRadius": 50,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow@24": {
      "elevation": 3,
      "shadowColor": "rgba(0, 0, 0, 0.1)"
    },
    "shadow-xl@18": {
      "elevation": 12.5,
      "shadowColor": "rgba(0, 0, 0, 0.1)"
    },
    "shadow-2xl@21": {
      "elevation": 25,
      "shadowColor": "rgba(0, 0, 0, 0.1)"
    },
    "shadow@25": {
      "shadowOffset": {
        "width": 0,
        "height": 2
      },
      "shadowRadius": 6,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow-xl@19": {
      "shadowOffset": {
        "width": 0,
        "height": 20
      },
      "shadowRadius": 25,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow-2xl@22": {
      "shadowOffset": {
        "width": 0,
        "height": 25
      },
      "shadowRadius": 50,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow@26": {
      "shadowOffset": {
        "width": 0,
        "height": 2
      },
      "shadowRadius": 6,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow-xl@20": {
      "shadowOffset": {
        "width": 0,
        "height": 20
      },
      "shadowRadius": 25,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow-2xl@23": {
      "shadowOffset": {
        "width": 0,
        "height": 25
      },
      "shadowRadius": 50,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow@27": {
      "elevation": 3,
      "shadowColor": "rgba(0, 0, 0, 0.1)"
    },
    "shadow-xl@21": {
      "elevation": 12.5,
      "shadowColor": "rgba(0, 0, 0, 0.1)"
    },
    "shadow-2xl@24": {
      "elevation": 25,
      "shadowColor": "rgba(0, 0, 0, 0.1)"
    },
    "shadow@28": {
      "shadowOffset": {
        "width": 0,
        "height": 2
      },
      "shadowRadius": 6,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow-xl@22": {
      "shadowOffset": {
        "width": 0,
        "height": 20
      },
      "shadowRadius": 25,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow-2xl@25": {
      "shadowOffset": {
        "width": 0,
        "height": 25
      },
      "shadowRadius": 50,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow@29": {
      "shadowOffset": {
        "width": 0,
        "height": 2
      },
      "shadowRadius": 6,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow-xl@23": {
      "shadowOffset": {
        "width": 0,
        "height": 20
      },
      "shadowRadius": 25,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow-2xl@26": {
      "shadowOffset": {
        "width": 0,
        "height": 25
      },
      "shadowRadius": 50,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow@30": {
      "elevation": 3,
      "shadowColor": "rgba(0, 0, 0, 0.1)"
    },
    "shadow-xl@24": {
      "elevation": 12.5,
      "shadowColor": "rgba(0, 0, 0, 0.1)"
    },
    "shadow-2xl@27": {
      "elevation": 25,
      "shadowColor": "rgba(0, 0, 0, 0.1)"
    },
    "shadow@31": {
      "shadowOffset": {
        "width": 0,
        "height": 2
      },
      "shadowRadius": 6,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow-xl@25": {
      "shadowOffset": {
        "width": 0,
        "height": 20
      },
      "shadowRadius": 25,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow-2xl@28": {
      "shadowOffset": {
        "width": 0,
        "height": 25
      },
      "shadowRadius": 50,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow@32": {
      "shadowOffset": {
        "width": 0,
        "height": 2
      },
      "shadowRadius": 6,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow-xl@26": {
      "shadowOffset": {
        "width": 0,
        "height": 20
      },
      "shadowRadius": 25,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow-2xl@29": {
      "shadowOffset": {
        "width": 0,
        "height": 25
      },
      "shadowRadius": 50,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow@33": {
      "elevation": 3,
      "shadowColor": "rgba(0, 0, 0, 0.1)"
    },
    "shadow-xl@27": {
      "elevation": 12.5,
      "shadowColor": "rgba(0, 0, 0, 0.1)"
    },
    "shadow-2xl@30": {
      "elevation": 25,
      "shadowColor": "rgba(0, 0, 0, 0.1)"
    },
    "shadow@34": {
      "shadowOffset": {
        "width": 0,
        "height": 2
      },
      "shadowRadius": 6,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow-xl@28": {
      "shadowOffset": {
        "width": 0,
        "height": 20
      },
      "shadowRadius": 25,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow-2xl@31": {
      "shadowOffset": {
        "width": 0,
        "height": 25
      },
      "shadowRadius": 50,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow@35": {
      "shadowOffset": {
        "width": 0,
        "height": 2
      },
      "shadowRadius": 6,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow-xl@29": {
      "shadowOffset": {
        "width": 0,
        "height": 20
      },
      "shadowRadius": 25,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow-2xl@32": {
      "shadowOffset": {
        "width": 0,
        "height": 25
      },
      "shadowRadius": 50,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow@36": {
      "elevation": 3,
      "shadowColor": "rgba(0, 0, 0, 0.1)"
    },
    "shadow-xl@30": {
      "elevation": 12.5,
      "shadowColor": "rgba(0, 0, 0, 0.1)"
    },
    "shadow-2xl@33": {
      "elevation": 25,
      "shadowColor": "rgba(0, 0, 0, 0.1)"
    },
    "shadow@37": {
      "shadowOffset": {
        "width": 0,
        "height": 2
      },
      "shadowRadius": 6,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow-xl@31": {
      "shadowOffset": {
        "width": 0,
        "height": 20
      },
      "shadowRadius": 25,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow-2xl@34": {
      "shadowOffset": {
        "width": 0,
        "height": 25
      },
      "shadowRadius": 50,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow@38": {
      "shadowOffset": {
        "width": 0,
        "height": 2
      },
      "shadowRadius": 6,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow-xl@32": {
      "shadowOffset": {
        "width": 0,
        "height": 20
      },
      "shadowRadius": 25,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow-2xl@35": {
      "shadowOffset": {
        "width": 0,
        "height": 25
      },
      "shadowRadius": 50,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "m-20": {
      "marginTop": 80,
      "marginRight": 80,
      "marginBottom": 80,
      "marginLeft": 80
    },
    "shadow@39": {
      "elevation": 3,
      "shadowColor": "rgba(0, 0, 0, 0.1)"
    },
    "shadow-xl@33": {
      "elevation": 12.5,
      "shadowColor": "rgba(0, 0, 0, 0.1)"
    },
    "shadow-2xl@36": {
      "elevation": 25,
      "shadowColor": "rgba(0, 0, 0, 0.1)"
    },
    "shadow@40": {
      "shadowOffset": {
        "width": 0,
        "height": 2
      },
      "shadowRadius": 6,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow-xl@34": {
      "shadowOffset": {
        "width": 0,
        "height": 20
      },
      "shadowRadius": 25,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow-2xl@37": {
      "shadowOffset": {
        "width": 0,
        "height": 25
      },
      "shadowRadius": 50,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow@41": {
      "shadowOffset": {
        "width": 0,
        "height": 2
      },
      "shadowRadius": 6,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow-xl@35": {
      "shadowOffset": {
        "width": 0,
        "height": 20
      },
      "shadowRadius": 25,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow-2xl@38": {
      "shadowOffset": {
        "width": 0,
        "height": 25
      },
      "shadowRadius": 50,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "mb-5": {
      "marginBottom": 20
    },
    "shadow@42": {
      "elevation": 3,
      "shadowColor": "rgba(0, 0, 0, 0.1)"
    },
    "shadow-xl@36": {
      "elevation": 12.5,
      "shadowColor": "rgba(0, 0, 0, 0.1)"
    },
    "shadow-2xl@39": {
      "elevation": 25,
      "shadowColor": "rgba(0, 0, 0, 0.1)"
    },
    "shadow@43": {
      "shadowOffset": {
        "width": 0,
        "height": 2
      },
      "shadowRadius": 6,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow-xl@37": {
      "shadowOffset": {
        "width": 0,
        "height": 20
      },
      "shadowRadius": 25,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow-2xl@40": {
      "shadowOffset": {
        "width": 0,
        "height": 25
      },
      "shadowRadius": 50,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow@44": {
      "shadowOffset": {
        "width": 0,
        "height": 2
      },
      "shadowRadius": 6,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow-xl@38": {
      "shadowOffset": {
        "width": 0,
        "height": 20
      },
      "shadowRadius": 25,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow-2xl@41": {
      "shadowOffset": {
        "width": 0,
        "height": 25
      },
      "shadowRadius": 50,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "mb-10": {
      "marginBottom": 40
    },
    "shadow@45": {
      "elevation": 3,
      "shadowColor": "rgba(0, 0, 0, 0.1)"
    },
    "shadow-xl@39": {
      "elevation": 12.5,
      "shadowColor": "rgba(0, 0, 0, 0.1)"
    },
    "shadow-2xl@42": {
      "elevation": 25,
      "shadowColor": "rgba(0, 0, 0, 0.1)"
    },
    "shadow@46": {
      "shadowOffset": {
        "width": 0,
        "height": 2
      },
      "shadowRadius": 6,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow-xl@40": {
      "shadowOffset": {
        "width": 0,
        "height": 20
      },
      "shadowRadius": 25,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow-2xl@43": {
      "shadowOffset": {
        "width": 0,
        "height": 25
      },
      "shadowRadius": 50,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow@47": {
      "shadowOffset": {
        "width": 0,
        "height": 2
      },
      "shadowRadius": 6,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow-xl@41": {
      "shadowOffset": {
        "width": 0,
        "height": 20
      },
      "shadowRadius": 25,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow-2xl@44": {
      "shadowOffset": {
        "width": 0,
        "height": 25
      },
      "shadowRadius": 50,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "mb-2.5": {
      "marginBottom": 10
    },
    "mb-2": {
      "marginBottom": 8
    },
    "shadow@48": {
      "elevation": 3,
      "shadowColor": "rgba(0, 0, 0, 0.1)"
    },
    "shadow-xl@42": {
      "elevation": 12.5,
      "shadowColor": "rgba(0, 0, 0, 0.1)"
    },
    "shadow-2xl@45": {
      "elevation": 25,
      "shadowColor": "rgba(0, 0, 0, 0.1)"
    },
    "shadow@49": {
      "shadowOffset": {
        "width": 0,
        "height": 2
      },
      "shadowRadius": 6,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow-xl@43": {
      "shadowOffset": {
        "width": 0,
        "height": 20
      },
      "shadowRadius": 25,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow-2xl@46": {
      "shadowOffset": {
        "width": 0,
        "height": 25
      },
      "shadowRadius": 50,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow@50": {
      "shadowOffset": {
        "width": 0,
        "height": 2
      },
      "shadowRadius": 6,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow-xl@44": {
      "shadowOffset": {
        "width": 0,
        "height": 20
      },
      "shadowRadius": 25,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow-2xl@47": {
      "shadowOffset": {
        "width": 0,
        "height": 25
      },
      "shadowRadius": 50,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "pb-10": {
      "paddingBottom": 40
    },
    "shadow@51": {
      "elevation": 3,
      "shadowColor": "rgba(0, 0, 0, 0.1)"
    },
    "shadow-xl@45": {
      "elevation": 12.5,
      "shadowColor": "rgba(0, 0, 0, 0.1)"
    },
    "shadow-2xl@48": {
      "elevation": 25,
      "shadowColor": "rgba(0, 0, 0, 0.1)"
    },
    "shadow@52": {
      "shadowOffset": {
        "width": 0,
        "height": 2
      },
      "shadowRadius": 6,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow-xl@46": {
      "shadowOffset": {
        "width": 0,
        "height": 20
      },
      "shadowRadius": 25,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow-2xl@49": {
      "shadowOffset": {
        "width": 0,
        "height": 25
      },
      "shadowRadius": 50,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow@53": {
      "shadowOffset": {
        "width": 0,
        "height": 2
      },
      "shadowRadius": 6,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow-xl@47": {
      "shadowOffset": {
        "width": 0,
        "height": 20
      },
      "shadowRadius": 25,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow-2xl@50": {
      "shadowOffset": {
        "width": 0,
        "height": 25
      },
      "shadowRadius": 50,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow@54": {
      "elevation": 3,
      "shadowColor": "rgba(0, 0, 0, 0.1)"
    },
    "shadow-xl@48": {
      "elevation": 12.5,
      "shadowColor": "rgba(0, 0, 0, 0.1)"
    },
    "shadow-2xl@51": {
      "elevation": 25,
      "shadowColor": "rgba(0, 0, 0, 0.1)"
    },
    "shadow@55": {
      "shadowOffset": {
        "width": 0,
        "height": 2
      },
      "shadowRadius": 6,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow-xl@49": {
      "shadowOffset": {
        "width": 0,
        "height": 20
      },
      "shadowRadius": 25,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow-2xl@52": {
      "shadowOffset": {
        "width": 0,
        "height": 25
      },
      "shadowRadius": 50,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow@56": {
      "shadowOffset": {
        "width": 0,
        "height": 2
      },
      "shadowRadius": 6,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow-xl@50": {
      "shadowOffset": {
        "width": 0,
        "height": 20
      },
      "shadowRadius": 25,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow-2xl@53": {
      "shadowOffset": {
        "width": 0,
        "height": 25
      },
      "shadowRadius": 50,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "m-0": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "shadow@57": {
      "elevation": 3,
      "shadowColor": "rgba(0, 0, 0, 0.1)"
    },
    "shadow-xl@51": {
      "elevation": 12.5,
      "shadowColor": "rgba(0, 0, 0, 0.1)"
    },
    "shadow-2xl@54": {
      "elevation": 25,
      "shadowColor": "rgba(0, 0, 0, 0.1)"
    },
    "shadow@58": {
      "shadowOffset": {
        "width": 0,
        "height": 2
      },
      "shadowRadius": 6,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow-xl@52": {
      "shadowOffset": {
        "width": 0,
        "height": 20
      },
      "shadowRadius": 25,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow-2xl@55": {
      "shadowOffset": {
        "width": 0,
        "height": 25
      },
      "shadowRadius": 50,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow@59": {
      "shadowOffset": {
        "width": 0,
        "height": 2
      },
      "shadowRadius": 6,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow-xl@53": {
      "shadowOffset": {
        "width": 0,
        "height": 20
      },
      "shadowRadius": 25,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow-2xl@56": {
      "shadowOffset": {
        "width": 0,
        "height": 25
      },
      "shadowRadius": 50,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    }
  },
  atRules: {
    "shadow": [[["media", "android"]], [["media", "ios"]], [["media", "web"]], [["media", "android"]], [["media", "ios"]], [["media", "web"]], [["media", "android"]], [["media", "ios"]], [["media", "web"]], [["media", "android"]], [["media", "ios"]], [["media", "web"]], [["media", "android"]], [["media", "ios"]], [["media", "web"]], [["media", "android"]], [["media", "ios"]], [["media", "web"]], [["media", "android"]], [["media", "ios"]], [["media", "web"]], [["media", "android"]], [["media", "ios"]], [["media", "web"]], [["media", "android"]], [["media", "ios"]], [["media", "web"]], [["media", "android"]], [["media", "ios"]], [["media", "web"]], [["media", "android"]], [["media", "ios"]], [["media", "web"]], [["media", "android"]], [["media", "ios"]], [["media", "web"]], [["media", "android"]], [["media", "ios"]], [["media", "web"]], [["media", "android"]], [["media", "ios"]], [["media", "web"]], [["media", "android"]], [["media", "ios"]], [["media", "web"]], [["media", "android"]], [["media", "ios"]], [["media", "web"]], [["media", "android"]], [["media", "ios"]], [["media", "web"]], [["media", "android"]], [["media", "ios"]], [["media", "web"]], [["media", "android"]], [["media", "ios"]], [["media", "web"]], [["media", "android"]], [["media", "ios"]], [["media", "web"]]],
    "shadow-2xl": [[["media", "android"]], [["media", "ios"]], [["media", "web"]], [["media", "android"]], [["media", "ios"]], [["media", "web"]], [["media", "android"]], [["media", "ios"]], [["media", "web"]], [["media", "android"]], [["media", "ios"]], [["media", "web"]], [["media", "android"]], [["media", "ios"]], [["media", "web"]], [["media", "android"]], [["media", "ios"]], [["media", "web"]], [["media", "android"]], [["media", "ios"]], [["media", "web"]], [["media", "android"]], [["media", "ios"]], [["media", "web"]], [["media", "android"]], [["media", "ios"]], [["media", "web"]], [["media", "android"]], [["media", "ios"]], [["media", "web"]], [["media", "android"]], [["media", "ios"]], [["media", "web"]], [["media", "android"]], [["media", "ios"]], [["media", "web"]], [["media", "android"]], [["media", "ios"]], [["media", "web"]], [["media", "android"]], [["media", "ios"]], [["media", "web"]], [["media", "android"]], [["media", "ios"]], [["media", "web"]], [["media", "android"]], [["media", "ios"]], [["media", "web"]], [["media", "android"]], [["media", "ios"]], [["media", "web"]], [["media", "android"]], [["media", "ios"]], [["media", "web"]], [["media", "android"]], [["media", "ios"]], [["media", "web"]]],
    "shadow-xl": [[["media", "android"]], [["media", "ios"]], [["media", "web"]], [["media", "android"]], [["media", "ios"]], [["media", "web"]], [["media", "android"]], [["media", "ios"]], [["media", "web"]], [["media", "android"]], [["media", "ios"]], [["media", "web"]], [["media", "android"]], [["media", "ios"]], [["media", "web"]], [["media", "android"]], [["media", "ios"]], [["media", "web"]], [["media", "android"]], [["media", "ios"]], [["media", "web"]], [["media", "android"]], [["media", "ios"]], [["media", "web"]], [["media", "android"]], [["media", "ios"]], [["media", "web"]], [["media", "android"]], [["media", "ios"]], [["media", "web"]], [["media", "android"]], [["media", "ios"]], [["media", "web"]], [["media", "android"]], [["media", "ios"]], [["media", "web"]], [["media", "android"]], [["media", "ios"]], [["media", "web"]], [["media", "android"]], [["media", "ios"]], [["media", "web"]], [["media", "android"]], [["media", "ios"]], [["media", "web"]], [["media", "android"]], [["media", "ios"]], [["media", "web"]], [["media", "android"]], [["media", "ios"]], [["media", "web"]], [["media", "android"]], [["media", "ios"]], [["media", "web"]]]
  }
});